version: '3.5'

services:

  # Deploy Config https://docs.docker.com/compose/compose-file/#mode
  # https://docs.docker.com/get-started/part5/
  kafka-java:
    image: localhost:5000/devops/demokafka:latest
    ports:
      - 8081:8080
    deploy:
      mode: replicated
replicas: 3